l=[1,2,3]
t=(4,5,6)
d={'a':7,'b':8,'c':9}
def f(*args,**kwargs):
    print (args,kwargs)
print ("first")
f()
print ("second")
f([1,2,3])
print ("third")
f(1,2,3,"groovy")
print ("four")
f(a=1,b=2,c=3)
print ("five")
f(a=1,b=2,c=3,zzz="hi")
print ("six")
f(1,2,3,a=1,b=2,c=3)
print ("seven")
f(*l,**d)
print ("eight")
f(*t,**d)
print ("nine")
f(1,2,*t)
print ("ten")
f(q="winning",**d)
print ("eleven")
f(1,2,*t,q="winning")
print ("twelve")
f(*t,1,2,q="winning")
print ("thirteen")
#f(**l)